app_register:
    path: /register
    controller: App\Module\User\Infrastructure\Http\RegistrationController::register
    methods: [ GET, POST ]

app_verify_email:
    path: /verify/email
    controller: App\Module\User\Infrastructure\Http\RegistrationController::verifyUserEmail
    methods: [ GET, POST ]

app_login:
    path: /login
    controller: App\Module\User\Infrastructure\Http\SecurityController::login
    methods: [ GET, POST ]

app_logout:
    path: /logout
    controller: App\Module\User\Infrastructure\Http\SecurityController::logout
    methods: [ GET, POST ]
